### ISSUE TITLE
This is a fork, please do not delete the original author of this lib

### ISSUE THREAD

**Issue by Nicolab** [yii2mod/yii2-ftp#17]
Please, be Fair-play...
Your project is a fork of https://github.com/Nicolab/php-ftp-client, you dont have right to remove the initial author name and put yours in the place as if you are the author of this. So I ask you to put a gain the name of the original author.

Please, append your name in the license if you want but do not delete the original author and the mention of the fork.

By fair-play and also for the users to know the history and parallel changes.

My PR https://github.com/yii2mod/yii2-ftp/pull/16 restore the original mentions, except the author section in the bottom of the original README.

Thanks

**Comment by disem** [comment]
Thanks for pointing this. At the time of building this repo I didn't realize how open source licensing works at all and I wasn't going to steal your code or something like this.
It just seemed like an easiest way to do what I wanted.

Your PR was merged and I hope that resolves this issue.
My apologies.

**Comment by Nicolab** [comment]
No problem I understand. Thanks for your reactivity and for your fair-play :+1: 
Just for info, packagist has not been updated, because the change of the hook system of packagist. The package will be updated when you will connect to packagist (login with Github).
