### ISSUE TITLE
Scandir not working if file contains spaces

### ISSUE THREAD

**Issue by WouterSlob** [yii2mod/yii2-ftp#3]
On my ftp I have a file named "20160416194445-Greenscreen studio.xml"

The scandir function returns a file with the name "20160416194445-Greenscreen"

The ftp_rawlist command returns this:
`-rw-r--r--    1 0        0             188 Apr 15 15:46 20160415174629-Greenscreen studio.xml`

In FTPClient parseRawList you should concatenate chunk 8->n to ensure you get the full name.

**Comment by ihorchepurnyi** [comment]
fixed by #4
