### ISSUE TITLE
Does not work when i ssh

### ISSUE THREAD

**Issue by nagbhushan** [yii2mod/yii2-ftp#7]
I tried using below.....but no luck

        $ftp = new \yii2mod\ftp\FtpClient();
        $host = 'xxx.xxx.xx.xx';
        $ftp->connect($host, true, 22222, 120);
        $ftp->login("xyz", "abcdef");

but was unable to connect...!!!!

Any help would be much appreciated.

**Comment by ihorchepurnyi** [comment]
Hi, now I don't have an ability to check it, but in my projects it works fine.
Also, via this extension you can't connect via ssh to the server. Only via ftp protocol.
